<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1
|Term|Brief Description|
|:---|:---|
|Subsetting|selecting parts of an array|
|Indexing|selecting 1 element of an array|
|Slicing|selecting multiple elements of an array|
|Masking|selecting element(s) of an array based on a certain criteria|

# Exercise 2

In [104]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
mask = np.array(np_array_2d[:,0].astype(int)%2)
np_array_2d = np_array_2d[mask==1]
answer_array = np_array_2d[:,1]
print(answer_array.tolist())

['A', 'C', 'E', 'G', 'I']


# Exercise 3

In [74]:
arr=[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]
np_arr=np.array(arr)
mask1=np_arr>50
mask3=(np_arr<50)*-1
mask=mask1+mask3
print(mask)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
